### PR TITLE
Prod GH Actions merge (WIP)

### PR DESCRIPTION
**Pull request by jsfillman**
This PR will add the :octocat: Actions to build & tag images, and deploy to GitHub Packages.

### Usage

1. Create a branch for changes.
2. Push to said branch.
3. Create a PR to merge to either `master`.
    - The `Docker Build` Action will build the initial test image.
    - Initial image will be saved to[ narrative-tracker-dev](https://github.com/kbase/narrative-traefiker/packages/341889).
5. Once image is successfully built, label the environment you wish to tag (`appdev`,`ci`, or `next`).
    - The `Tag Environments` Action will tag only the environment you specify.
    - The image will be pushed (with the same Image ID), to the corresponding [package registry](https://github.com/kbase/narrative-traefiker/packages).
6. Once all tests in the various environments have been finalized, merge the PR.
    - If the merge is to `master`, the `Tag Production Post-Merge` Action will tag and push to [narrative-traefiker-prod](https://github.com/kbase/narrative-traefiker/packages/341901) (still with the same Image ID).

#### Notes
- For security purposes, it's important to enable branch restrictions on a repo, requiring a PR to merge to `master`. As such, branch restrictions have been enabled on this repo.
- Attempting to tag _during_ PR creation will fail, as the initial `-dev` image hasn't yet been built. This is by design.
- Tagging multiple environments at the same time will cause the image to be tagged multiple times. This is harmless, but is worth mentioning.
- Since we use SHAs and PR#s for reference, one can safely have multiple test branches concurrently.
- These Actions are designed to provide a full audit trail of builds:
    - Initial image is tagged with the origin branch name, the PR#, and the commit SHA.
    - The `appdev`, `ci`, and `next` images are also tagged with the branch, PR#, and the commit SHA.
    - The final `-prod` image is tagged with the name of the PR (e.g. "Prod GH Actions merge") and `latest`.
      - Since the PR is closed and (ideally) the origin branch deleted _before_ tagging, using the origin SHA an PR# gets overly complicated.

### CODE REVIEW

**Review by sychan — CHANGES_REQUESTED** [review]
Hi Jason,
    Please look at the build script at : https://github.com/kbase/narrative-traefiker/blob/master/hooks/build

    It has a series of variables that are passed into the docker build to set the image LABEL fields. I see that you are setting a bunch of related variables but I don't see where they are passed into the build.
    Almost all of the docker images that were converted to use Travis or Dockerhub use the same variables for image labels, please make sure they still work in the new build pipeline.

**Comment by sychan** [comment]
Looking at the changes, I don't see where the variables you have set from the environment get pushed into the docker build, did I just miss it?

**Comment by sychan** [comment]
I see that you added a lot of tags, but those values are supposed to be in the docker image metadata as labels that you can see with a "docker inspect IMAGE_NAME"

**Comment by jsfillman** [comment]
The SHA, origin branch, and PR# will all be tagged.  I can add date if that's critical for current setup, although SHA & PR# are more reliable markers.

Was running into issue getting the SHA & PR in the final prod image, which I resolved last night in another branch. Doing some cleanup and submitting here. Marking this as WIP until then.

Will verify the metadata issue. My initial discussions with @kkellerlbl had centered around tagging.

**Comment by jsfillman** [comment]
Closing this PR after our requirements discussion today.
New work will occur in [my fork](https://github.com/jsfillman/narrative-traefiker) until ready for review/merge is ready.

**Pull request closed without merging**
